### ISSUE TITLE
Add in an e.g. Utilities" text panel component containing documentation and hyperlinks to the readme / sDNA manual (or other solution)

### ISSUE THREAD

**Issue by JamesParrott** [JamesParrott/sDNA_GH#78]

**Comment by fiftysevendegreesofrad** [comment]
Probably not. Can you wait until I get the open source sdna+ out, and then
we'll use that manual (which will also be readthedocs but maybe elsewhere)

**Comment by JamesParrott** [comment]
Just let me know when, and I'll update the Readme.txt component.
